GET http://localhost:5162/games

###

GET http://localhost:5162/games/1

###

POST http://localhost:5162/games
Content-Type: application/json

{
    "title": "Final Fantasy VII Remake",
    "genreId": 3,
    "price": 59.99,
    "developer": "Square Enix",
    "publisher": "Square Enix",
    "releaseDate": "2020-04-10"
}

###

PUT http://localhost:5162/games/1
Content-Type: application/json

{
  "id": 5,
  "title": "The Witcher 3: Wild Hunt (100% Off)",
  "genreId": 2,
  "price": 0,
  "developer": "CD Projekt Red",
  "publisher": "CD Projekt",
  "releaseDate": "2015-05-19"
}

###

DELETE http://localhost:5162/games/3
